Add Testing
Alabi12/Rails_BlogApp pull request #6
Opened 2023-03-06 23:36 UTC by Alabi12

# Summary
This PR contains the following;
- [ ] Add RSpec as a gem to your project.

- [ ] Create a Request spec file for all your controllers.

- [ ] Make sure that for each action you check:

- If response status was correct.

- If a correct template was rendered.

- If the response body includes correct placeholder text.

2023-03-06 23:47 UTC, brytebee requested changes
Hi, @Alabi12👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great UI design.✔️
- App functions as it should.✔️

##

Good job so far coming so far with the progress you've made! 💪💪
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-06 23:47 UTC, brytebee commented on spec/requests/posts_controller_spec.rb
> +  end
You are required to test the index page that renders all posts, which you have correctly done. 👏 
However, you are also required to also test the show page for a single post as well as a single user. Kindly add them.

![image](https://user-images.githubusercontent.com/27709832/223282427-5495ed32-baac-4cc4-a121-45ff67124826.png)

2023-03-07 09:38 UTC, Davidosky007 requested changes
Hi @Alabi12 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* No linter errors 👍 
* Well written PR description 👍 
* Good looking readme file 👍 

 ## Required Changes ♻️
* Nice Job working on the previous CR's request but you forgot to add one test, Kindly check add them as its a requirement 🙏 
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidosky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-07 09:38 UTC, Davidosky007 commented on spec/requests/posts_controller_spec.rb
> +    it 'renders show template with correct placeholder text' do
* Kindly add also a test that checks If the response body includes the correct placeholder text as its a requirement 
![image](https://user-images.githubusercontent.com/52497246/223382196-3fe53fcc-66c6-443d-8242-c59963ef4156.png)

2023-03-07 09:38 UTC, Davidosky007 commented on spec/requests/users_controller_spec.rb
> +    it 'renders show template with correct placeholder text' do
* Kindly add also a test that checks If the response body includes the correct placeholder text as its a requirement 
![image](https://user-images.githubusercontent.com/52497246/223382196-3fe53fcc-66c6-443d-8242-c59963ef4156.png)

2023-03-07 11:04 UTC, mikethreels approved these changes
Hi Robert, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- linters are passing
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-07 13:01 UTC, merged